tasks:
  - name: install-dependencies
    before: |
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl https://katapod-file-store.s3.us-west-1.amazonaws.com/ds201/lab10-environment.tar.gz \
        --output environment.tar.gz
      tar xf environment.tar.gz
    init: |
    command: | 
      clear
github:
  prebuilds:
    main: true
ports:
  - port: 1-9999
    onOpen: ignore
vscode:
   extensions:
    - https://github.com/hemidactylus/katapod/releases/download/1.1.0-beta2/katapod-1.1.0-beta2.vsix
image: gitpod/workspace-full:2023-02-27-14-39-56